### ISSUE TITLE
<pre><code> instead of <pre>

### ISSUE THREAD

**Issue by mesqueeb** [commit-intl/micro-down#14]
https://github.com/commit-intl/micro-down/blob/22bae9a28cf0c88685142580ad153420320fd5bb/src/index.js#L47

In order to make **PrismJS syntax highlighting** work, it requires all code blocks to be formatted like so:
```
<pre>
  <code>
// the code
  </code>
</pre>
```

But I believe micro-down only uses `<pre>` without `<code>`.

My request is that snarkdown uses `<pre><code>` by default OR via an option.

From the PrismJS docs:

> Encourages good author practices. Other highlighters encourage or even force you to use elements that are semantically wrong, like `<pre>` (on its own) or `<script>`. Prism forces you to use the correct element for marking up code: `<code>`. On its own for inline code, or inside a `<pre>` for blocks of code. In addition, the language is defined through the way recommended in the HTML5 draft: through a `language-xxxx` class.

https://prismjs.com/#features-full

**Comment by mesqueeb** [comment]
@ShynRou what do you think of this change? If OK I can try to make a PR.

**Comment by ShynRou** [comment]
@mesqueeb Sorry for the way to late response.
You are right an option for <pre><code> makes sense. 
I'll add it.

**Comment by ShynRou** [comment]
@mesqueeb Just release version 1.6.0 now includes an options parameter with a preCode flag.

Thank you for your input, I really appreciate it. :)
